export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRY: '15m',
  REFRESH_TOKEN_EXPIRY: '7d',
  BCRYPT_ROUNDS: 12,
  RATE_LIMIT_TTL: 60,
  RATE_LIMIT_MAX: 10,
  OTP_LENGTH: 6,
  OTP_EXPIRY_MINUTES: 5,
  PASSWORD_MIN_LENGTH: 8,
} as const;
